import libs = libboost-date-time%lib{boost_date_time}

lib{crails-logger}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_LOGGER_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_LOGGER_SHARED_BUILD

# Export options.
#
lib{crails-logger}:
{
  cxx.export.poptions = "-I$out_root/libcrails-logger/" "-I$src_root/libcrails-logger/"
  cxx.export.libs = $intf_libs
}

liba{crails-logger}: cxx.export.poptions += -DLIBCRAILS_LOGGER_STATIC
libs{crails-logger}: cxx.export.poptions += -DLIBCRAILS_LOGGER_SHARED

if $version.pre_release
  lib{crails-logger}: bin.lib.version = "-$version.project_id"
else
  lib{crails-logger}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
